### Q1: Gaussian Naive Bayes Classifier

In [16]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [31]:
data = load_iris()
X = data.data
Y = data.target

In [17]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=19)

In [23]:
GaussNB = GaussianNB()
GaussNB.fit(X_train,Y_train)
Y_predict = GaussNB.predict(X_test)

### Performace Evaluation of Classifier

In [28]:
from sklearn.metrics import accuracy_score, confusion_matrix,precision_score, recall_score, f1_score, roc_curve

In [43]:
cnf_matrix = confusion_matrix(Y_test, Y_predict)
print(cnf_matrix)

[[14  0  0]
 [ 0 16  0]
 [ 0  3 12]]


In [34]:
accuracy_score(Y_test, Y_predict)

0.9333333333333333

In [39]:
precision_score(Y_test, Y_predict, average = 'micro')

0.9333333333333333

In [40]:
recall_score(Y_test, Y_predict, average = 'micro')

0.9333333333333333

In [42]:
f1_score(Y_test, Y_predict, average = 'micro')

0.9333333333333333

In [45]:
FP = cnf_matrix.sum(axis=0) - np.diag(cnf_matrix)  
FN = cnf_matrix.sum(axis=1) - np.diag(cnf_matrix)
TP = np.diag(cnf_matrix)
TN = cnf_matrix.sum() - (FP + FN + TP)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
# Specificity or true negative rate
TNR = TN/(TN+FP) 
# Fall out or false positive rate
FPR = FP/(FP+TN)
# False negative rate
FNR = FN/(TP+FN)
print(TPR,TNR,FPR,FNR)

[1.  1.  0.8] [1.         0.89655172 1.        ] [0.         0.10344828 0.        ] [0.  0.  0.2]
